# Generated by Django 4.1.1 on 2022-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='images')),
                ('cantidad_porcion', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Cantidad porción (en gramos)')),
                ('hidratos_carbono', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Hidratos de Carbono (en gramos)')),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Proteinas (en gramos)')),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Grasas (en gramos)')),
                ('energia', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Energia (kilocalorias)')),
            ],
            options={
                'verbose_name_plural': 'Comidas',
            },
        ),
    ]
