# Generated by Django 4.1.1 on 2022-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='alimento',
            field=models.ManyToManyField(to='alimento.alimento'),
        ),
        migrations.AddField(
            model_name='comida',
            name='dia',
            field=models.CharField(blank=True, choices=[('desayuno_merienda_bebidas', 'Desayuno/Merienda - Bebidas'), ('desayuno_merienda_comida', 'Desayuno/Merienda - Comida'), ('almuerzo_cena_entrada', 'Almuerzo/Cena - Entrada'), ('almuerzo_cena_plato_principal', 'Almuerzo/Cena - Plato Principal'), ('almuerzo_cena_postre', 'Almuerzo/Cena - Postre')], max_length=50),
        ),
    ]
