# Generated by Django 4.1.1 on 2022-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_comida_alimento_comida_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='dia',
        ),
        migrations.AddField(
            model_name='comida',
            name='horario',
            field=models.CharField(blank=True, choices=[('desayuno_merienda_bebidas', 'Desayuno/Merienda - Bebidas'), ('desayuno_merienda_comida', 'Desayuno/Merienda - Comida'), ('almuerzo_cena_entrada', 'Almuerzo/Cena - Entrada'), ('almuerzo_cena_plato_principal', 'Almuerzo/Cena - Plato Principal'), ('almuerzo_cena_postre', 'Almuerzo/Cena - Postre')], max_length=50, verbose_name='Horario a servir'),
        ),
    ]
