# Generated by Django 4.1.1 on 2023-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0003_remove_comida_dia_comida_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='horario',
            field=models.CharField(choices=[('desayuno_merienda_bebidas', 'Desayuno/Merienda - Bebidas'), ('desayuno_merienda_comida', 'Desayuno/Merienda - Comida'), ('almuerzo_cena_entrada', 'Almuerzo/Cena - Entrada'), ('almuerzo_cena_plato_principal', 'Almuerzo/Cena - Plato Principal'), ('almuerzo_cena_postre', 'Almuerzo/Cena - Postre')], max_length=50, verbose_name='Horario a servir'),
        ),
    ]
