# Generated by Django 4.1.1 on 2023-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
        ('comida', '0004_alter_comida_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='alimento',
            field=models.ManyToManyField(blank=True, to='alimento.alimento'),
        ),
    ]
