# Generated by Django 4.1.1 on 2023-01-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_alter_comida_alimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='cantidad_porcion',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='energia',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='grasas',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='hidratos_carbono',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='proteinas',
        ),
    ]
