# Generated by Django 4.1.1 on 2022-11-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantidad_trabajadores_comedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadtrabajadorescomedor',
            name='rango',
            field=models.CharField(max_length=100, verbose_name='Rango'),
        ),
    ]
