# Generated by Django 4.1.1 on 2023-01-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='grasas_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Grasas Totales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='sodio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Sodio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='cantidad_porcion',
            field=models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Cantidad de Referencia'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Calorias'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas',
            field=models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Grasas Saturadas'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='hidratos_carbono',
            field=models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Proteinas'),
        ),
    ]
