# Generated by Django 4.1.1 on 2023-07-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0002_alimento_grasas_totales_alimento_sodio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='energia',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Kilocalorias'),
        ),
    ]
