# Generated by Django 4.1.1 on 2023-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0003_alter_alimento_energia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='cantidad_porcion',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Cantidad de Referencia'),
        ),
    ]
