# Generated by Django 4.1.1 on 2024-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0004_alter_alimento_cantidad_porcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidades',
            field=models.ManyToManyField(to='alimento.unidad', verbose_name='Unidades'),
        ),
    ]
