# Generated by Django 4.1.1 on 2024-09-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0004_alter_alimento_cantidad_porcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoSARA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_porcion', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('hidratos_carbono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proteinas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grasas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grasas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('energia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sodio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
