# Generated by Django 4.1.1 on 2024-10-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alimento", "0005_alimentosara"),
        ("alimento", "0006_alter_alimento_unidades"),
    ]

    operations = []
