# Generated by Django 4.1.1 on 2022-11-25 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0001_initial'),
        ('comida', '0002_comida_alimento_comida_dia'),
        ('organizacion', '0005_organizacion_tipo_organizacion'),
        ('comedor', '0002_remove_funcionamientocomedor_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de inicio de actividad')),
                ('cantidad_rango_1', models.IntegerField(verbose_name='Cantidad de Comensales - Rango 1')),
                ('cantidad_rango_2', models.IntegerField(verbose_name='Cantidad de Comensales - Rango 2')),
                ('cantidad_rango_3', models.IntegerField(verbose_name='Cantidad de Comensales - Rango 3')),
                ('cantidad_rango_4', models.IntegerField(verbose_name='Cantidad de Comensales - Rango 4')),
                ('funcionamiento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('olla_popular', 'Olla Popular')], max_length=30)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
                ('responsable_comedor', models.ForeignKey(limit_choices_to={'groups__name': 'Responsable Comedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
            },
        ),
        migrations.CreateModel(
            name='ComidaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoComidaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento')),
                ('comida_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.comidaencuesta')),
            ],
        ),
    ]
