# Generated by Django 4.1.1 on 2023-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_alimentocomidaencuesta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentocomidaencuesta',
            name='comida_encuesta',
        ),
        migrations.AlterField(
            model_name='alimentocomidaencuesta',
            name='alimento',
            field=models.CharField(max_length=12, verbose_name='alimento'),
        ),
    ]
