# Generated by Django 4.1.1 on 2023-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
        ('encuesta', '0004_comidaencuesta_alimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlimentoComidaEncuesta',
        ),
        migrations.AlterField(
            model_name='comidaencuesta',
            name='alimento',
            field=models.ManyToManyField(blank=True, null=True, to='alimento.alimento'),
        ),
    ]
