# Generated by Django 4.1.1 on 2023-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
        ('encuesta', '0005_delete_alimentocomidaencuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidaencuesta',
            name='alimento',
            field=models.ManyToManyField(to='alimento.alimento'),
        ),
    ]
