# Generated by Django 4.1.1 on 2023-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
        ('encuesta', '0006_alter_comidaencuesta_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidaencuesta',
            name='alimento',
            field=models.ManyToManyField(blank=True, to='alimento.alimento'),
        ),
    ]
