# Generated by Django 4.1.1 on 2023-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_alter_comidaencuesta_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='funcionamiento',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30),
        ),
    ]
