# Generated by Django 4.1.1 on 2023-01-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
        ('encuesta', '0008_alter_encuesta_funcionamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=5)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento')),
            ],
            options={
                'verbose_name_plural': 'Alimentos de una encuesta',
            },
        ),
        migrations.AlterField(
            model_name='comidaencuesta',
            name='alimento',
            field=models.ManyToManyField(blank=True, to='encuesta.alimentoencuesta'),
        ),
    ]
