# Generated by Django 4.1.1 on 2023-01-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_alter_comida_alimento'),
        ('encuesta', '0009_alimentoencuesta_alter_comidaencuesta_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentoencuesta',
            name='comida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comida.comida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentoencuesta',
            name='encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ComidaEncuesta',
        ),
    ]
