# Generated by Django 4.1.1 on 2023-01-27 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0010_alimentoencuesta_comida_alimentoencuesta_encuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentoencuesta',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Comensales - Rango 1'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Comensales - Rango 2'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_3',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Comensales - Rango 3'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_4',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Comensales - Rango 4'),
        ),
    ]
