# Generated by Django 4.1.1 on 2023-01-27 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0011_alter_alimentoencuesta_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 1'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 2'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_3',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 3'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='cantidad_rango_4',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 4'),
        ),
    ]
