# Generated by Django 4.1.1 on 2023-01-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0006_alter_funcionamientocomedor_funcionamiento'),
        ('encuesta', '0012_alter_encuesta_cantidad_rango_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSeSirvioEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('funcionamiento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
            ],
            options={
                'verbose_name_plural': 'Encuestas que no se sirvieron',
            },
        ),
    ]
