# Generated by Django 4.1.1 on 2023-01-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0006_alter_funcionamientocomedor_funcionamiento'),
        ('encuesta', '0013_nosesirvioencuesta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nosesirvioencuesta',
            unique_together={('fecha', 'comedor', 'funcionamiento')},
        ),
    ]
