# Generated by Django 4.1.1 on 2024-09-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alimento", "0006_alter_alimento_unidades"),
        ("encuesta", "0015_alimentoencuesta_unidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentoencuesta",
            name="unidad",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="alimento.unidad",
            ),
        ),
    ]
