# Generated by Django 4.1.1 on 2022-11-23 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responsable_organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsableorganizacion',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Responsable Organizacion'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
