# Generated by Django 4.1.1 on 2022-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='organizacion_images')),
                ('estado', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Organizaciones',
            },
        ),
    ]
