# Generated by Django 4.1.1 on 2022-10-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(upload_to='../organizacion_images'),
        ),
    ]
