# Generated by Django 4.1.1 on 2022-10-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_alter_organizacion_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='es_organizacion_regional',
            field=models.BooleanField(default=False, verbose_name='Es regional'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='organizacion_superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion'),
        ),
    ]
