# Generated by Django 4.1.1 on 2022-11-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_organizacion', '0001_initial'),
        ('organizacion', '0004_organizacion_es_organizacion_regional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_organizacion.tipoorganizacion'),
            preserve_default=False,
        ),
    ]
