# Generated by Django 4.1.1 on 2024-01-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_remove_comida_cantidad_porcion_remove_comida_energia_and_more'),
        ('comedor', '0009_alter_comedor_actividades'),
        ('organizacion', '0005_organizacion_tipo_organizacion'),
        ('reporte', '0002_reportesraciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porciones', models.FloatField()),
                ('hidratos', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasasSaturadas', models.FloatField()),
                ('grasasTotales', models.FloatField()),
                ('kilocalorias', models.FloatField()),
                ('sodio', models.FloatField()),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
            ],
            options={
                'verbose_name_plural': 'Reportes Nutricional',
            },
        ),
    ]
