# Generated by Django 4.1.1 on 2024-02-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0014_alter_nosesirvioencuesta_unique_together'),
        ('reporte', '0003_reportenutricional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportenutricional',
            name='comida',
        ),
        migrations.AddField(
            model_name='reportenutricional',
            name='encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta'),
            preserve_default=False,
        ),
    ]
