# Generated by Django 4.1.1 on 2024-11-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0010_remove_comedor_gobierno_local'),
        ('localidad', '0002_remove_localidad_gobierno_local'),
        ('gobierno_local', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GobiernoLocal',
        ),
    ]
