# Generated by Django 4.1.1 on 2022-11-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('organizacion', '0005_organizacion_tipo_organizacion'),
        ('fuente_agua_comedor', '0001_initial'),
        ('localidad', '0001_initial'),
        ('tipo_energia_comedor', '0001_initial'),
        ('asistentes_diarios_comedor', '0001_initial'),
        ('provincia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cantidad_trabajadores_comedor', '0002_alter_cantidadtrabajadorescomedor_rango'),
        ('servicio_comedor', '0001_initial'),
        ('gobierno_local', '0001_initial'),
        ('actividad_complementaria_comedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero', models.CharField(max_length=15, verbose_name='Número')),
                ('entre_calles', models.CharField(max_length=200, verbose_name='Entre Calles')),
                ('latitud', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Longitud')),
                ('ubicacion_georreferencial', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Ubicacion GEO')),
                ('fecha_inicio_actividad', models.DateField(verbose_name='Fecha de inicio de actividad')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fuente_agua_potable', models.BooleanField(default=False, verbose_name='Fuente de Agua Potable')),
                ('asistentes_diarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistentes_diarios_comedor.asistentesdiarioscomedor')),
                ('cantidad_trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantidad_trabajadores_comedor.cantidadtrabajadorescomedor')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('fuente_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuente_agua_comedor.fuenteaguacomedor')),
                ('gobierno_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobierno_local.gobiernolocal')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad.localidad')),
                ('organizacion_regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provincia.provincia')),
                ('responsable_comedor', models.ForeignKey(limit_choices_to={'groups__name': 'Responsable Comedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio_comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_comedor.serviciocomedor')),
                ('tipos_energia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_energia_comedor.tipoenergiacomedor')),
            ],
            options={
                'verbose_name_plural': 'Comedores',
            },
        ),
        migrations.CreateModel(
            name='OtrasActividadesComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_actividad', models.DateField(verbose_name='Fecha de inicio de actividad')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad_complementaria_comedor.actividadcomplementariacomedor')),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionamientoComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=9)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_comedor.serviciocomedor')),
            ],
        ),
    ]
