# Generated by Django 4.1.1 on 2022-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionamientocomedor',
            name='servicio',
        ),
        migrations.AddField(
            model_name='funcionamientocomedor',
            name='funcionamiento',
            field=models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('olla_popular', 'Olla Popular')], max_length=30),
        ),
    ]
