# Generated by Django 4.1.1 on 2022-11-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0002_remove_funcionamientocomedor_servicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionamientocomedor',
            options={'verbose_name_plural': 'Funcionamiento de Comedores'},
        ),
        migrations.AlterModelOptions(
            name='otrasactividadescomedor',
            options={'verbose_name_plural': 'Otras actividades de Comedores'},
        ),
    ]
