# Generated by Django 4.1.1 on 2022-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad_complementaria_comedor', '0001_initial'),
        ('comedor', '0003_alter_funcionamientocomedor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otrasactividadescomedor',
            name='actividad',
        ),
        migrations.AddField(
            model_name='otrasactividadescomedor',
            name='actividades',
            field=models.ManyToManyField(to='actividad_complementaria_comedor.actividadcomplementariacomedor'),
        ),
    ]
