# Generated by Django 4.1.1 on 2022-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad_complementaria_comedor', '0001_initial'),
        ('comedor', '0004_remove_otrasactividadescomedor_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedor',
            name='actividades',
            field=models.ManyToManyField(to='actividad_complementaria_comedor.actividadcomplementariacomedor'),
        ),
        migrations.DeleteModel(
            name='OtrasActividadesComedor',
        ),
    ]
