# Generated by Django 4.1.1 on 2023-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0005_comedor_actividades_delete_otrasactividadescomedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionamientocomedor',
            name='funcionamiento',
            field=models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30),
        ),
    ]
