# Generated by Django 4.1.1 on 2023-02-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes_diarios_comedor', '0001_initial'),
        ('localidad', '0001_initial'),
        ('actividad_complementaria_comedor', '0001_initial'),
        ('servicio_comedor', '0001_initial'),
        ('departamento', '0001_initial'),
        ('cantidad_trabajadores_comedor', '0002_alter_cantidadtrabajadorescomedor_rango'),
        ('tipo_energia_comedor', '0001_initial'),
        ('fuente_agua_comedor', '0001_initial'),
        ('gobierno_local', '0001_initial'),
        ('comedor', '0006_alter_funcionamientocomedor_funcionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='actividades',
            field=models.ManyToManyField(blank=True, null=True, to='actividad_complementaria_comedor.actividadcomplementariacomedor'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='asistentes_diarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistentes_diarios_comedor.asistentesdiarioscomedor'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='cantidad_trabajadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantidad_trabajadores_comedor.cantidadtrabajadorescomedor'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='entre_calles',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entre Calles'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='fecha_inicio_actividad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de actividad'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='fuente_agua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuente_agua_comedor.fuenteaguacomedor'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='fuente_agua_potable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fuente de Agua Potable'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='gobierno_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gobierno_local.gobiernolocal'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.localidad'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='servicio_comedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio_comedor.serviciocomedor'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='tipos_energia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_energia_comedor.tipoenergiacomedor'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='ubicacion_georreferencial',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='Ubicacion GEO'),
        ),
    ]
