# Generated by Django 4.1.1 on 2023-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad_complementaria_comedor', '0001_initial'),
        ('comedor', '0007_alter_comedor_actividades_alter_comedor_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='actividades',
            field=models.ManyToManyField(to='actividad_complementaria_comedor.actividadcomplementariacomedor'),
        ),
    ]
