# Generated by Django 4.1.1 on 2024-11-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0009_alter_comedor_actividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedor',
            name='gobierno_local',
        ),
    ]
