# Generated by Django 4.1.1 on 2023-02-03 17:19


from django.db import migrations
from django.core.management import call_command

fixture = 'export_nombre'


def crear_registros(apps, schema_editor):
	call_command('loaddata', fixture, app_label='user')

class Migration(migrations.Migration):
	dependencies = [
		('user', '0002_alter_usuariopersonalizado_genero'),
	]

operations = [
	migrations.RunPython(crear_registros)
]
