# Generated by Django 4.1.1 on 2023-04-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usuariopersonalizado_email'),
        ('user', '0004_auto_20230411_1413'),
    ]

    operations = [
    ]
