# Generated by Django 4.1.1 on 2024-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_merge_20230413_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariopersonalizado",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
