diccionario_administrador = [
{'app_label': 'comedor',
             'app_url': '/admin/comedor/',
             'has_module_perms': True,
             'models': [{'add_url': '/admin/comedor/comedor/add/',
                         'admin_url': '/admin/comedor/comedor/',
                         'model': "<class 'comedor.models.Comedor'>",
                         'name': 'Comedores',
                         'object_name': 'Comedor',
                         'perms': {'add': True,
                                   'change': True,
                                   'delete': True,
                                   'view': True},
                         'view_only': True}],
             'name': 'Comedor'},
{'app_label': 'comida',
            'app_url': '/admin/comida/',
            'has_module_perms': True,
            'models': [{'add_url': '/admin/alimento/alimento/add/',
						'admin_url': '/admin/alimento/alimento/',
						'model': "<class 'alimento.models.Alimento'>",
						'name': 'Alimentos',
						'object_name': 'Alimento',
						'perms': {'add': True,
								  'change': True,
								  'delete': True,
								  'view': True},
						'view_only': True},
					   {'add_url': '/admin/comida/comida/add/',
                        'admin_url': '/admin/comida/comida/',
                        'model': "<class 'comida.models.Comida'>",
                        'name': 'Comidas',
                        'object_name': 'Comida',
                        'perms': {'add': True,
                                  'change': True,
                                  'delete': True,
                                  'view': True},
                        'view_only': True},
					   ],
            'name': 'Comidas y Alimentos'},
{'app_label': 'actividad_complementaria_comedor',
			  'app_url': '/admin/actividad_complementaria_comedor/',
			  'has_module_perms': True,
			  'models': [{'add_url': '/admin/actividad_complementaria_comedor/actividadcomplementariacomedor/add/',
						  'admin_url': '/admin/actividad_complementaria_comedor/actividadcomplementariacomedor/',
						  'model': "<class 'actividad_complementaria_comedor.models.ActividadComplementariaComedor'>",
						  'name': 'Actividades '
								  'Complementarias '
								  'Comedores',
						  'object_name': 'ActividadComplementariaComedor',
						  'perms': {'add': True,
									'change': True,
									'delete': True,
									'view': True},
						  'view_only': True},
						{'add_url': '/admin/asistentes_diarios_comedor/asistentesdiarioscomedor/add/',
						'admin_url': '/admin/asistentes_diarios_comedor/asistentesdiarioscomedor/',
						'model': "<class 'asistentes_diarios_comedor.models.AsistentesDiariosComedor'>",
						'name': 'Asistentes diarios de los '
								'Comedores',
						'object_name': 'AsistentesDiariosComedor',
						'perms': {'add': True,
								  'change': True,
								  'delete': True,
								  'view': True},
						'view_only': True},
						{'add_url': '/admin/cantidad_trabajadores_comedor/cantidadtrabajadorescomedor/add/',
					   'admin_url': '/admin/cantidad_trabajadores_comedor/cantidadtrabajadorescomedor/',
					   'model': "<class 'cantidad_trabajadores_comedor.models.CantidadTrabajadoresComedor'>",
					   'name': 'Cantidad de '
							   'Trabajadores de los '
							   'Comedores',
					   'object_name': 'CantidadTrabajadoresComedor',
					   'perms': {'add': True,
								 'change': True,
								 'delete': True,
								 'view': True},
					   'view_only': True},
						{'add_url': '/admin/fuente_agua_comedor/fuenteaguacomedor/add/',
						 'admin_url': '/admin/fuente_agua_comedor/fuenteaguacomedor/',
						 'model': "<class 'fuente_agua_comedor.models.FuenteAguaComedor'>",
						 'name': 'Fuentes de Agua de los Comedores',
						 'object_name': 'FuenteAguaComedor',
						 'perms': {'add': True,
								   'change': True,
								   'delete': True,
								   'view': True},
						 'view_only': True},
						 {'add_url': '/admin/genero/genero/add/',
						  'admin_url': '/admin/genero/genero/',
						  'model': "<class 'genero.models.Genero'>",
						  'name': 'Géneros',
						  'object_name': 'Genero',
						  'perms': {'add': True,
									'change': True,
									'delete': True,
									'view': True},
						  'view_only': True},
						 {'add_url': '/admin/servicio_comedor/serviciocomedor/add/',
						  'admin_url': '/admin/servicio_comedor/serviciocomedor/',
						  'model': "<class 'servicio_comedor.models.ServicioComedor'>",
						  'name': 'Servicios Comedores',
						  'object_name': 'ServicioComedor',
						  'perms': {'add': True,
									'change': True,
									'delete': True,
									'view': True},
						  'view_only': True},
						{'add_url': '/admin/tipo_organizacion/tipoorganizacion/add/',
					   'admin_url': '/admin/tipo_organizacion/tipoorganizacion/',
					   'model': "<class 'tipo_organizacion.models.TipoOrganizacion'>",
					   'name': 'Tipo Organizaciones',
					   'object_name': 'TipoOrganizacion',
					   'perms': {'add': True,
								 'change': True,
								 'delete': True,
								 'view': True},
					   'view_only': True},
						{'add_url': '/admin/tipo_energia_comedor/tipoenergiacomedor/add/',
					  'admin_url': '/admin/tipo_energia_comedor/tipoenergiacomedor/',
					  'model': "<class 'tipo_energia_comedor.models.TipoEnergiaComedor'>",
					  'name': 'Tipos de Energia de los '
							  'Comedores',
					  'object_name': 'TipoEnergiaComedor',
					  'perms': {'add': True,
								'change': True,
								'delete': True,
								'view': True},
					  'view_only': True},],
			  'name': 'Datos Generales'},
{'app_label': 'encuesta',
              'app_url': '/admin/encuesta/',
              'has_module_perms': True,
              'models': [{'add_url': '',
					  'admin_url': '/admin/encuesta/alimentoencuesta/',
					  'model': "<class 'encuesta.models.AlimentoEncuesta'>",
					  'name': 'Alimentos de una encuesta',
					  'object_name': 'AlimentoEncuesta',
					  'perms': {'add': True,
								'change': True,
								'delete': True,
								'view': True},
					  'view_only': True},
						 {'add_url': '',
                          'admin_url': '/admin/encuesta/encuesta/',
                          'model': "<class 'encuesta.models.Encuesta'>",
                          'name': 'Encuestas',
                          'object_name': 'Encuesta',
                          'perms': {'add': True,
                                    'change': True,
                                    'delete': True,
                                    'view': True},
                          'view_only': True},
					 {'add_url': '',
					  'admin_url': '/admin/encuesta/nosesirvioencuesta/',
					  'model': "<class 'encuesta.models.NoSeSirvioEncuesta'>",
					  'name': 'Encuestas que no se sirvieron',
					  'object_name': 'NoSeSirvioEncuesta',
					  'perms': {'add': True,
								'change': True,
								'delete': True,
								'view': True},
					  'view_only': True},
					 ],
              				'name': 'Encuesta'},
						{'app_label': 'departamento',
						  'app_url': '/admin/departamento/',
						  'has_module_perms': True,
						  'models': [{'add_url': '/admin/departamento/departamento/add/',
						  'admin_url': '/admin/departamento/departamento/',
						  'model': "<class 'departamento.models.Departamento'>",
						  'name': 'Departamentos',
						  'object_name': 'Departamento',
						  'perms': {'add': True,
									'change': True,
									'delete': True,
									'view': True},
						  'view_only': True},
						 {'add_url': '/admin/gobierno_local/gobiernolocal/add/',
						  'admin_url': '/admin/gobierno_local/gobiernolocal/',
						  'model': "<class 'gobierno_local.models.GobiernoLocal'>",
						  'name': 'Gobiernos Locales',
						  'object_name': 'GobiernoLocal',
						  'perms': {'add': True,
									'change': True,
									'delete': True,
									'view': True},
						  'view_only': True},
						{'add_url': '/admin/localidad/localidad/add/',
                           'admin_url': '/admin/localidad/localidad/',
                           'model': "<class 'localidad.models.Localidad'>",
                           'name': 'Localidades',
                           'object_name': 'Localidad',
                           'perms': {'add': True,
                                     'change': True,
                                     'delete': True,
                                     'view': True},
                           'view_only': True},
						{'add_url': '/admin/provincia/provincia/add/',
                           'admin_url': '/admin/provincia/provincia/',
                           'model': "<class 'provincia.models.Provincia'>",
                           'name': 'Provincias',
                           'object_name': 'Provincia',
                           'perms': {'add': True,
                                     'change': True,
                                     'delete': True,
                                     'view': True},
                           'view_only': True}],
			  'name': 'Geolocalizacion'},
#{'app_label': 'admin_interface',
#				 'app_url': '/admin/admin_interface/',
#				 'has_module_perms': True,
#				 'models': [{'add_url': '/admin/admin_interface/theme/add/',
#							 'admin_url': '/admin/admin_interface/theme/',
#							 'model': "<class 'admin_interface.models.Theme'>",
#							 'name': 'Temas',
#							 'object_name': 'Theme',
#							 'perms': {'add': True,
#									   'change': True,
#									   'delete': True,
#									   'view': True},
#							 'view_only': False}],
#				 'name': 'Interfaz de administración'},
{'app_label': 'organizacion',
			  'app_url': '/admin/organizacion/',
			  'has_module_perms': True,
			  'models': [{'add_url': '/admin/organizacion/organizacion/add/',
						  'admin_url': '/admin/organizacion/organizacion/',
						  'model': "<class 'organizacion.models.Organizacion'>",
						  'name': 'Organizaciones',
						  'object_name': 'Organizacion',
						  'perms': {'add': True,
									'change': True,
									'delete': True,
									'view': True},
						  'view_only': True}],
			  'name': 'Organizacion'},
{'app_label': 'reporte',
             'app_url': '/admin/reporte/',
             'has_module_perms': True,
             'models': [{'add_url': '',
                         'admin_url': '/admin/reporte/reportesraciones/',
                         'model': "<class 'reporte.models.ReportesRaciones'>",
                         'name': 'Reportes de raciones',
                         'object_name': 'ReportesRaciones',
                         'perms': {'add': True,
                                   'change': True,
                                   'delete': True,
                                   'view': True},
                         'view_only': True},
						{'add_url': '',
                         'admin_url': '/admin/reporte/reportesgenerales/',
                         'model': "<class 'reporte.models.ReportesGenerales'>",
                         'name': 'Reportes generales',
                         'object_name': 'ReportesGenerales',
                         'perms': {'add': True,
                                   'change': True,
                                   'delete': True,
                                   'view': True},
                         'view_only': True},
                        ],
             'name': 'Reporte'},
#{'app_label': 'sites',
#           'app_url': '/admin/sites/',
#           'has_module_perms': True,
#           'models': [{'add_url': '/admin/sites/site/add/',
#                       'admin_url': '/admin/sites/site/',
#                       'model': "<class 'django.contrib.sites.models.Site'>",
#                       'name': 'Sitios',
#                       'object_name': 'Site',
#                       'perms': {'add': True,
#                                 'change': True,
#                                 'delete': True,
#                                 'view': True},
#                       'view_only': False}],
#           'name': 'Sitios'},
{'app_label': 'account',
             'app_url': '/admin/account/',
             'has_module_perms': True,
             'models': [#{'add_url': '/admin/account/emailaddress/add/',
                        # 'admin_url': '/admin/account/emailaddress/',
                        # 'model': "<class 'allauth.account.models.EmailAddress'>",
                        # 'name': 'Correos electrónicos',
                        # 'object_name': 'EmailAddress',
                        # 'perms': {'add': True,
                        #           'change': True,
                        #           'delete': True,
                        #           'view': True},
                        # 'view_only': False},
				 		#{'add_url': '/admin/auth/group/add/',
						#  'admin_url': '/admin/auth/group/',
						#  'model': "<class 'django.contrib.auth.models.Group'>",
						#  'name': 'Grupos',
						#  'object_name': 'Group',
						#  'perms': {'add': True,
						#			'change': True,
						#			'delete': True,
						#			'view': True},
						#  'view_only': False},
						# {'add_url': '/admin/auth/permission/add/',
						#  'admin_url': '/admin/auth/permission/',
						#  'model': "<class 'django.contrib.auth.models.Permission'>",
						#  'name': 'Permisos',
						#  'object_name': 'Permission',
						#  'perms': {'add': True,
						#			'change': True,
						#			'delete': True,
						#			'view': True},
						#  'view_only': False},
						{'add_url': '/admin/user/usuariopersonalizado/add/',
						 'admin_url': '/admin/user/usuariopersonalizado/',
						 'model': "<class 'user.models.UsuarioPersonalizado'>",
						 'name': 'Usuarios',
						 'object_name': 'UsuarioPersonalizado',
						 'perms': {'add': True,
								   'change': True,
								   'delete': True,
								   'view': True},
						 'view_only': True},
						#{'add_url': '/admin/authtoken/tokenproxy/add/',
						#   'admin_url': '/admin/authtoken/tokenproxy/',
						#   'model': "<class 'rest_framework.authtoken.models.TokenProxy'>",
						#   'name': 'Tokens',
						#   'object_name': 'TokenProxy',
						#   'perms': {'add': True,
						#			 'change': True,
						#			 'delete': True,
						#			 'view': True},
						#  'view_only': False}
						],
						 'name': 'Usuario'},
]
