# Generated by Django 4.1.1 on 2024-11-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='gobierno_local',
        ),
    ]
